/** Cover verse: Arabic is always shown; English sits under it as originally. */
export const QURAN = {
  basmala: 'بسم الله الرحمن الرحيم',
  verse:
    'وَمِنْ آيَاتِهِ أَنْ خَلَقَ لَكُم مِنْ أَنْفُسِكُمْ أَزْوَاجًا لِتَسْكُنُوا إِلَيْهَا وَجَعَلَ بَيْنَكُمْ مَوَدَّةً وَرَحْمَةً ۚ إِنَّ فِي ذَلِكَ لَآيَاتٍ لِقَوْمٍ يَتَفَكَّرُونَ',
  verseEn:
    'And among His signs is that He created for you spouses from yourselves, that you may find tranquility in them; and He placed between you compassion and mercy. Indeed in that are signs for people who reflect.',
  ref: 'سورة الروم · ٢١',
  refEn: 'Surah Ar-Rum · 30:21',
}

/** Central invitation content — edit names, date, venue, assets, and translations here. */

export const INVITATION = {
  audioSrc: '/-JUDHox3Pd8.mp3',
  audioFallback: '/audio/wedding-music.mp3',
  coupleImage: '/images/couple.png',
  mapsUrl:
    'https://www.google.com/maps/search/?api=1&query=Al-Ali+Al-Azeem+Mosque+Almazah+Cairo+Egypt',
  rsvpUrl:
    'https://script.google.com/macros/s/AKfycbxekTfzqJxesAikvHwmiI4gvPj3DdHHE93OFgdCjhHN1P-7SOuHsYcA0QvOhezeOza24A/exec',
  weddingDate: '2026-09-20T21:30:00',
  endDate: '2026-09-20T23:30:00',
  venueImages: [
    { src: '/images/venue/exterior.jpg', key: 'exterior' },
    { src: '/images/venue/interior.jpg', key: 'interior' },
    { src: '/images/venue/dome.jpg', key: 'dome' },
    { src: '/images/venue/details.jpg', key: 'details' },
  ],
  copy: {
    en: {
      documentTitle: 'Mohamed & Sondos — Katb Kitab',
      kicker: 'With gratitude · together with our families',
      nameFirst: 'Mohamed',
      nameSecond: 'Sondos',
      namesLine: 'Mohamed & Sondos',
      namesScript: 'Mohamed & Sondos',
      inviteLine: 'Request the pleasure of your company',
      coupleAlt: 'Mohamed and Sondos as children, embracing and smiling',
      openInvite: 'Open invitation',
      eventLabel: 'Katb Kitab',
      eventKicker: 'The celebration',
      date: '20 September 2026',
      dateShort: '20 · 09 · 2026',
      time: '9:30 PM',
      weekday: 'Saturday',
      countdown: 'Counting down',
      days: 'Days',
      hours: 'Hours',
      minutes: 'Minutes',
      seconds: 'Seconds',
      addCalendar: 'Google Calendar',
      calendarLabel: 'Katb Kitab day',
      saveTheDate: 'Save the date',
      scrollHint: 'Scroll or use arrow keys',
      venueKicker: 'The venue',
      venueName: 'Al-Ali Al-Azeem Mosque',
      venueArabicName: 'مسجد العلي العظيم',
      venueArea: 'Almazah, Cairo, Egypt',
      venueDescription:
        'A contemporary Egyptian mosque of ivory marble, quiet arches, and warm light in Almazah.',
      venueNote: 'Kindly arrive a few minutes early.',
      venueAlts: {
        exterior: 'Exterior of Al-Ali Al-Azeem Mosque in Almazah',
        interior: 'Ivory marble arches inside Al-Ali Al-Azeem Mosque',
        dome: 'Main dome and chandelier at Al-Ali Al-Azeem Mosque',
        details: 'Marble courtyard details at Al-Ali Al-Azeem Mosque',
      },
      locationCta: 'View Location',
      rsvpKicker: 'RSVP',
      rsvpName: 'Full name',
      rsvpNamePh: 'Your name',
      rsvpAttend: 'Will you attend?',
      rsvpYes: 'Joyfully accepts',
      rsvpNo: 'Regretfully declines',
      rsvpMessage: 'Message (optional)',
      rsvpMessagePh: 'A kind word for the couple…',
      rsvpSubmit: 'Submit',
      rsvpSending: 'Sending…',
      rsvpError: 'Something went wrong. Please try again.',
      rsvpThanksYes: 'We cannot wait',
      rsvpThanksNo: 'Forever in our hearts',
      rsvpReceived:
        'Your yes means the world to us. We will be so glad to have you with us as we begin this blessed chapter.',
      rsvpDeclined:
        'Thank you for sharing this with us so kindly. You will be missed, and you remain in our prayers on this day.',
      rsvpThanks: 'With love,',
      rsvpEdit: 'Edit response',
      closing: 'With love',
      navHome: 'Home',
      navVenue: 'Venue',
      navRsvp: 'RSVP',
      langEn: 'EN',
      langAr: 'AR',
      langLabel: 'Language',
      musicPlay: 'Play music',
      musicPause: 'Pause music',
      musicHint: 'Tap to play music',
    },
    ar: {
      documentTitle: 'محمد و سندس — عقد القرآن',
      kicker: 'بمباركة أهلهما',
      nameFirst: 'محمد',
      nameSecond: 'سندس',
      namesLine: 'محمد & سندس',
      namesScript: 'محمد & سندس',
      inviteLine: 'يتشرفان بدعوتكم لحضور عقد القرآن',
      coupleAlt: 'محمد وسندس في الطفولة، يتعانقان ويبتسمان',
      openInvite: 'افتحوا الدعوة',
      eventLabel: 'عقد القرآن',
      eventKicker: 'المناسبة',
      date: '20 سبتمبر 2026',
      dateShort: '20 · 09 · 2026',
      time: '9:30 مساءً',
      weekday: 'السبت',
      countdown: 'العد التنازلي',
      days: 'يوم',
      hours: 'ساعة',
      minutes: 'دقيقة',
      seconds: 'ثانية',
      addCalendar: 'أضيفوا للتقويم',
      calendarLabel: 'يوم عقد القرآن',
      saveTheDate: 'احفظوا الموعد',
      scrollHint: 'مرروا للأسفل',
      venueKicker: 'المكان',
      venueName: 'مسجد العلي العظيم',
      venueArabicName: 'مسجد العلي العظيم',
      venueArea: 'ألماظة، القاهرة، مصر',
      venueDescription: 'صرح إسلامي معاصر من الرخام العاجي والأقواس الهادئة في ألماظة.',
      venueNote: 'يرجى الحضور قبل الموعد بدقائق.',
      venueAlts: {
        exterior: 'واجهة مسجد العلي العظيم في ألماظة',
        interior: 'أقواس رخامية داخل مسجد العلي العظيم',
        dome: 'القبة الرئيسية داخل مسجد العلي العظيم',
        details: 'تفاصيل الصحن الرخامي في مسجد العلي العظيم',
      },
      locationCta: 'عرض الموقع',
      rsvpKicker: 'تأكيد الحضور',
      rsvpName: 'الاسم الكامل',
      rsvpNamePh: 'اسمكم',
      rsvpAttend: 'هل ستحضرون؟',
      rsvpYes: 'يسعدنا الحضور',
      rsvpNo: 'نعتذر عن الحضور',
      rsvpMessage: 'رسالة (اختياري)',
      rsvpMessagePh: 'كلمة طيبة للعروسين…',
      rsvpSubmit: 'إرسال',
      rsvpSending: 'جارٍ الإرسال…',
      rsvpError: 'حدث خطأ، حاولوا مرة أخرى.',
      rsvpThanksYes: 'حضوركم يسعدنا',
      rsvpThanksNo: 'ستبقون في قلوبنا',
      rsvpReceived:
        'شكرًا لقلوبكم الطيبة. ننتظر لقياكم بفرح في يوم عقد قرآننا، ليكتمل فرحنا بكم.',
      rsvpDeclined:
        'شكرًا لإعلامنا بلطفكم. نفتقدكم، وتبقون في دعائنا في هذا اليوم المبارك.',
      rsvpThanks: 'بكل حب،',
      rsvpEdit: 'تعديل الرد',
      closing: 'بكل حب',
      navHome: 'الرئيسية',
      navVenue: 'المكان',
      navRsvp: 'الحضور',
      langEn: 'EN',
      langAr: 'AR',
      langLabel: 'اللغة',
      musicPlay: 'تشغيل الموسيقى',
      musicPause: 'إيقاف الموسيقى',
      musicHint: 'اضغطوا لتشغيل الموسيقى',
    },
  },
}

export function detectBrowserLanguage() {
  if (typeof navigator === 'undefined') return 'en'
  const candidates = [
    navigator.language,
    ...(Array.isArray(navigator.languages) ? navigator.languages : []),
  ]
    .filter(Boolean)
    .map((code) => String(code).toLowerCase())
  return candidates.some((code) => code === 'ar' || code.startsWith('ar-')) ? 'ar' : 'en'
}
